# Use the latest version of Ruby.
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

# Double quotes are preferable for me.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# API methods should have get as a prefix.
Naming/AccessorMethodName:
  Enabled: false

# Double quotes are preferable for me.
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# No reason for me to have this here.
Style/MissingRespondToMissing:
  Enabled: false

# Most of these metrics are useless.
Metrics/ClassLength:
  Enabled: false

# Most of these metrics are useless.
Metrics/PerceivedComplexity:
  Enabled: false

# Most of these metrics are useless.
Metrics/CyclomaticComplexity:
  Enabled: false

# Most of these metrics are useless.
Metrics/ParameterLists:
  Enabled: false

# Most of these metrics are useless.
Metrics/MethodLength:
  Enabled: false

# Most of these metrics are useless.
Metrics/BlockLength:
  Enabled: false

# Most of these metrics are useless.
Metrics/AbcSize:
  Enabled: false

# I don't like the extra end it introduces.
Style/IfUnlessModifier:
  Enabled: false

# Kinda need to have this due to regex stuff.
Lint/DuplicateBranch:
  Exclude:
  - lib/calliope/client.rb

# Again, kinda need this due to regex stuff.
Layout/LineLength:
  Exclude:
  - lib/calliope/client.rb

# Partially disabled so my lazy ass doesn't forget.
Lint/UnusedMethodArgument:
  Exclude:
  - lib/calliope/client.rb

# Always use the percent sign for regex matching.
Style/RegexpLiteral:
  EnforcedStyle: "percent_r"

# Semi-colon syntax isn't that bad.
Style/Semicolon:
  Enabled: false