# Use the latest version of Ruby.
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

# Double quotes are preferable for me.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# API methods should have get as a prefix.
Naming/AccessorMethodName:
  Enabled: false

# Double quotes are preferable for me.
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Kinda need to have this due to regex stuff.
Lint/DuplicateBranch:
  Exclude:
  - lib/calliope/client.rb

# Again, kinda need this due to regex stuff.
Layout/LineLength:
  Exclude:
  - lib/calliope/client.rb
  - lib/calliope/model/playable.rb

# Partially disabled so my lazy ass doesn't forget.
Lint/UnusedMethodArgument:
  Exclude:
  - lib/calliope/client.rb

# Always use the percent sign for regex matching.
Style/RegexpLiteral:
  EnforcedStyle: "percent_r"

# Most of these metrics are useless.
Metrics:
  Enabled: false

# I don't like the extra end it introduces.
Style/IfUnlessModifier:
  Enabled: false

# A literal is more readable for me.
Style/EmptyLiteral:
  Enabled: false

# Semicolons can be useful for one-liners.
Style/Semicolon:
  Enabled: false